### PR TITLE
NODE-1134: using pino as debug logger

### PR DESCRIPTION
**Pull request by helio-frota**

### CODE REVIEW

**Comment by helio-frota** [comment]
coveralls seems flakey

**Review by lholmquist — COMMENTED** [review]
this is the output when using these changes:

```
~/develop/rhoar-nodejs-boosters/nodejs-rest-http(main*) » ./node_modules/.bin/nodeshift                                       lucasholmquist@lincolnhawk2
{"level":30,"time":1618594637017,"pid":24857,"hostname":"lincolnhawk2","0":"loading configuration"}
{"level":30,"time":1618594637020,"pid":24857,"hostname":"lincolnhawk2","0":"No login.json file found"}
{"level":30,"time":1618594637073,"pid":24857,"hostname":"lincolnhawk2","0":"using namespace lholmqui-stage at https://api.sandbox.x8i5.p1.openshiftapps.com:6443"}
{"level":30,"time":1618594637075,"pid":24857,"hostname":"lincolnhawk2","0":"creating archive of package.json, app.js, public, bin, LICENSE, licenses"}
{"level":30,"time":1618594637228,"pid":24857,"hostname":"lincolnhawk2","0":"creating build configuration nodejs-rest-http-s2i"}
{"level":30,"time":1618594637229,"pid":24857,"hostname":"lincolnhawk2","0":"Using the Source Build Strategy"}
{"level":30,"time":1618594637229,"pid":24857,"hostname":"lincolnhawk2","0":"Using s2i image registry.access.redhat.com/ubi8/nodejs-14 with tag latest"}
{"level":30,"time":1618594637502,"pid":24857,"hostname":"lincolnhawk2","0":"creating ImageStream nodejs-rest-http"}
{"level":30,"time":1618594637616,"pid":24857,"hostname":"lincolnhawk2","0":"uploading binary archive /home/lucasholmquist/develop/rhoar-nodejs-boosters/nodejs-rest-http/tmp/nodeshift/build/archive.tar"}
{"level":30,"time":1618594643138,"pid":24857,"hostname":"lincolnhawk2","0":"binary upload complete"}
{"level":30,"time":1618594643138,"pid":24857,"hostname":"lincolnhawk2","0":"waiting for build to finish"}
{"level":30,"time":1618594767734,"pid":24857,"hostname":"lincolnhawk2","0":"build nodejs-rest-http-s2i-1 complete"}
{"level":30,"time":1618594767783,"pid":24857,"hostname":"lincolnhawk2","0":"openshift.yaml and openshift.json written to /home/lucasholmquist/develop/rhoar-nodejs-boosters/nodejs-rest-http/tmp/nodeshift/resource/"}
{"level":30,"time":1618594767894,"pid":24857,"hostname":"lincolnhawk2","0":"creating new service nodejs-rest-http"}
{"level":30,"time":1618594767907,"pid":24857,"hostname":"lincolnhawk2","0":"creating deployment configuration nodejs-rest-http"}
{"level":30,"time":1618594767912,"pid":24857,"hostname":"lincolnhawk2","0":"creating new route nodejs-rest-http"}
{"level":30,"time":1618594768030,"pid":24857,"hostname":"lincolnhawk2","0":"route host mapping nodejs-rest-http-lholmqui-stage.apps.sandbox.x8i5.p1.openshiftapps.com"}
{"level":30,"time":1618594768031,"pid":24857,"hostname":"lincolnhawk2","0":"complete"}
```

Which doesn't feel as useful as the current way it is done.  

There is also an issue where the TRACE logs are not being streamed to the console.  in fact, they aren't output at all.

I don't have any objection to moving to a better logger, but I think we should try to make it work as similar to what we currently have as much as possible

**Comment by helio-frota** [comment]
That is strange.
This is the screenshot I shared days ago:


Other CLI tools under nodeshift organization are not using pino due to the custom generated output.
And as we still having issues with that then maybe it is good to not merge.

**Comment by helio-frota** [comment]
I forgot to mention another thing, we have no gains in terms of performance in CLI tools like nodeshift , npcheck, and license-reporter for example.

And just to send content to stdout we don't really need to be in a JSON format.

I'm going to close this PR :+1:

**Pull request closed without merging**
