### PR TITLE
Replacing rimraf with custom module

### PR DESCRIPTION
**Pull request by alexalikiotis**

### CODE REVIEW

**Comment by alexalikiotis** [comment]
@lholmquist Probably more tests required in `utils/rmrf.js` itself.

**Comment by lholmquist** [comment]
Yea,  we need to actually test the `rmrf` function.  Have you you tried to actually test locally that it works with a test project

**Comment by alexalikiotis** [comment]
@lholmquist Yeah, I've tested the rmrf function as a single unit and in my forked nodeshift itself and it works fine (same result as rimraf). The question is how we can write tests for a module that has side-effects with the disk. 🤔

**Comment by lholmquist** [comment]
probably will need to mock those api's that do disk operations

**Comment by alexalikiotis** [comment]
I can give this approach a try 👍

**Comment by lholmquist** [comment]
you can run `npm run coverage:html` and then open the index.html in the coverage folder to get a good visual of what coverage is missing

**Pull request merged**
