### PR TITLE
WIP: Adding web-app flag

### PR DESCRIPTION
**Pull request by alexalikiotis**
I'm opening this PR just for a first review. No tests or documentation updates are implemented yet.

### CODE REVIEW

**Comment by lholmquist** [comment]
Code looks good.  looks like there is a linting issue though, thats why the ci failed

once we get some tests and docs, we can merge.  i also clicked a button to take off the draft status by accident, but i don't know how to get it back :)

**Comment by alexalikiotis** [comment]
Great! I'll find and fix the linting issue tomorrow and I'll continue with tests and docs :)

**Comment by lholmquist** [comment]
The only other comment i have is probably creating a branch on your fork, instead of doing things in master

**Comment by alexalikiotis** [comment]
@lholmquist that's a very good idea! I can revert back my forked master branch and create a new branch, re-do the above work there, create another PR and continue with tests and doc updates there. What do you think ?? :)

**Comment by lholmquist** [comment]
if you want.  but not necessary.  just an FYI for next time :)

**Comment by alexalikiotis** [comment]
I'm closing this PR so I can create a new one from the new branch I created.

**Pull request closed without merging**
