### PR TITLE
Adding web-app flag

### PR DESCRIPTION
**Pull request by alexalikiotis**
I'm re-opening the PR from the new branch 'web-app-flag'. Still WIP but the linting error is fixed and I also updated the docs, so the only thing left is writing the tests :)

### CODE REVIEW

**Comment by lholmquist** [comment]
looking pretty good,  and for the test, you should be able to copy something from https://github.com/nodeshift/nodeshift/blob/master/test/build-strategy-test.js or https://github.com/nodeshift/nodeshift/blob/master/test/definitions-tests/build-strategy-test.js  which just realized should be merged together.  I'll create another issue for that

**Comment by alexalikiotis** [comment]
@lholmquist I finished writing the tests (It's just a single test though). I think the PR is ready for a final review and merge :)

**Comment by lholmquist** [comment]
@alexalikiotis since we merged #397, the test file you added your tests to doesn't exist anymore :)  can you rebase this PR with master.

**Comment by alexalikiotis** [comment]
@lholmquist Done!

**Pull request merged**
